### ISSUE TITLE
Round 1: A list of common crops

### ISSUE THREAD

**Issue by andru** [openfarmcc/open-crop-icons#2]
If you're interested in helping out, choose an unclaimed crop below and add a comment to this issue to claim it!  Once you've got something to share for feedback, open up a new issue.
- [ ] acorn squash `in progress` #14
- [ ] artichoke (green)
- [ ] basil
- [ ] bean (runner) 
- [ ] bean (french) 
- [ ] bean (mung)
- [ ] broccoli `in progress` #7 
- [ ] butternut squash `in progress` #13 
- [ ] cabbage (loose leafed) 
- [ ] cabbage (winter) `in progress` #13 
- [ ] cabbage (red) 
- [ ] capsicum red/green (bell pepper) `in progress` #13 
- [ ] cauliflower (white) `claimed` @andru
- [ ] beet `in progress` #14
- [ ] carrot `claimed` #4 
- [ ] chard `claimed` https://github.com/openfarmcc/open-crop-icons/issues/2#issuecomment-202286033
- [ ] chili (habanero) `claimed` https://github.com/openfarmcc/open-crop-icons/issues/2#issuecomment-172737770
- [ ] chili pepper (jalepeño?)
- [x] corn #6 
- [ ] cucumber
- [ ] eggplant (aubergine) `in progress` #7
- [ ] lemon `in progress` #4 
- [ ] lettuce
- [ ] kale
- [ ] onion `claimed` #4 
- [ ] pak choy `claimed https://github.com/openfarmcc/open-crop-icons/issues/2#issuecomment-202286033`
- [ ] parsnip `claimed` https://github.com/openfarmcc/open-crop-icons/issues/2#issuecomment-174216376
- [ ] pea `in progress` #7 
- [ ] pea (snow pea) `in progress` #14
- [ ] potato
- [x] pumpkin (the classic big orange winter squash) #6 
- [ ] radish `in progress` #4 
- [ ] romaine lettuce
- [ ] strawberry `claimed` https://github.com/openfarmcc/open-crop-icons/issues/2#issuecomment-174216376
- [ ] swede
- [ ] sweet potato
- [ ] tomatillo
- [x] tomato #5 
- [x] cherry tomato #5 
- [ ] spinach `claimed` https://github.com/openfarmcc/open-crop-icons/issues/2#issuecomment-174216376
- [ ] yam
- [ ] yellow crookneck squash `in progress` #13
- [ ] zucchini (courgette)

Feel free to suggest changes and additions!

**Comment by andru** [comment]
@neynah I compiled a list of the most common fruits and veg; don't be scared off by the increased size - whatever you can contribute will be amazing!

Not sure how best to collaborate here, as I'm also working on a couple.  Currently doing broccoli and red capsicum.  Maybe we should open up issues for each icon to communicate that we've claimed it? And then we could post WIP shots if we like.  Or if that seems like overkill, maybe an issue for each batch like `WIP: cucumber, onion, corn`.

**Comment by roryaronson** [comment]
Yewww! I think you just nailed how to claim 'em @andru - just posting what one is working on right here seems to work nicely :+1:. Once this list is exhausted we can move onto a second batch in another issue!

**Comment by neynah** [comment]
Thanks! I already started on a lemon one... hope that is OK.

**Comment by simonv3** [comment]
There's actually a lot of people who like growing lemons and would like to grow lemons in my friend circle! Not so much oranges - but I wouldn't make assumptions about what's a priority or not :). 

Basically - to me a priority vegetable or fruit is one that someone thought of. 

I made some changes to the original list post @andru (added some "in progress" tags with a reference to the comment claiming them). Tell me what you think (@roryaronson, @neynah)

**Comment by neynah** [comment]
Yikes, already some overlap. I can take broccoli out of my queue then.

**Comment by jneubrand** [comment]
I can do tomato/cherry tomato/chili.
For chili: I'll probably make a red one, a green one, and perhaps a habanero.

**Comment by neynah** [comment]
Also, I like the "in progress" tags with links to the issues. :+1:

**Comment by simonv3** [comment]
Yeah, I was hoping to make them look like tags by using the `code`(`) markup ticks, but unfortunately that didn't parse the URL.

**Comment by jneubrand** [comment]
Code inside the url works!
[`google`](google.com) `{   ['google'](google.com)  with backticks }` as opposed to `[google](google.com)`

**Comment by simonv3** [comment]
:stars: the more you know!

Edit: Actually, it's not even necessary.

**Comment by jsimplicio** [comment]
Hey all! I want to help out with these as well. I can take corn and pumpkin for now :) :+1:

**Comment by simonv3** [comment]
I've marked them as claimed :)

**Comment by andru** [comment]
It's amazing to see how quickly we're getting through this list! Great work everyone!

**Comment by andru** [comment]
Ta-da! Tomato and Cherry Tomato are our first completed icons - thanks @jneubrand!

**Comment by jneubrand** [comment]
You're welcome!

**Comment by jsimplicio** [comment]
I'm gonna be taking strawberry, parsnip, and spinach if no problem :)

**Comment by andru** [comment]
@jsimplicio all yours :)

**Comment by andru** [comment]
Just taken butternut squash (which I'm currently both sowing for next year and feasting on from last!), capsicum (belll pepper), crookneck and winter cabbage. See #13

**Comment by linchocolatte** [comment]
hey there! just wondering if you guys still need any icon designs for the crops? I'll be glad to help out! (:

Can I take pak choy and chard? haha

**Comment by simonv3** [comment]
Hey @linchocolatte, definitely take a jab at any crops you want to design! I'll mark you as doing pak choy and chard :)

**Comment by RajeInkworks** [comment]
Hi I have started to design cucumber, yam , potato, sweet potato. And I have completed cucumber, yam and potato. If you tell me the size of the icon will resize and commit the crops icon till I completed after getting your reviews. 
![crops](https://cloud.githubusercontent.com/assets/10882609/25315123/d2bb4a8a-286d-11e7-899b-a107d218ffab.png)

**Comment by roryaronson** [comment]
Hey @Rajalashmi thanks for jumping in and contributing!

I apologize (to everyone) for not posting in this repository sooner, but through my work with [FarmBot](https://farmbot.io) we've been developing a bunch of crop icons and uploading them to OpenFarm directly, including icons for these three crops and 100+ others! While no crop icons are currently used on the OpenFarm interface, you can see them on the crop edit pages:

* https://openfarm.cc/en/crops/cucumber/edit
* https://openfarm.cc/en/crops/potato/edit
* https://openfarm.cc/en/crops/japanese-yam/edit
* https://openfarm.cc/en/crops/sweet-potato/edit

And you can see all of the icons we've made so far [here](https://drive.google.com/drive/folders/0Bzm0yyP7JMLiM0U4ZkdmNG9rVjQ?usp=sharing). Some have not yet been uploaded to OpenFarm. These should probably be added to this repository too, which I'll open up another issue for to figure out the best way to do that.

**Comment by Tropicalrambler** [comment]
@roryaronson I am a FarmBot owner and currently am working on an agriculture module for [frappe/erpnext](url), also an Open Source project.  At some point I wish to manage my planting tasks for my hydroponic farm with FarmBot and ERPNext: hopefully by 2019, as my ambitions outweigh my capacity to do everything at once.  My question is if you guys have an updated list, or the google docs list provided in the main repo/issues is the most exhaustive yet? Also, I'd be willing at some point to  be add them here with a PR from a fork of this repo. Let me know how progress is going.  Regards form a CalPoly alumni!

**Comment by Erioldoesdesign** [comment]
Hey folks! this issue thread looks super active and I was wondering if you want the associated open source design job updated or whether you want it closed? https://opensourcedesign.net/jobs/jobs/2015-09-SVG-plant-icons

**Comment by roryaronson** [comment]
@Erioldoesdesign you can go ahead and close the job. While this thread was really active, the OpenFarm project as a whole has seen little activity the last few years. Most development (including the design of the vast majority of OpenFarm's current crop icons) stems from FarmBot in-house or contract work these days.
